import jsPDF from 'jspdf';

type Props = {
  routeName: string;
  distance: number;
  fuel: number;
  cost: number;
  eta: string;
  waveHeight: number | null;
  hours: number;
};

export function generateVoyageReport(data: Props) {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text('🚢 Voyage Intelligence Report', 20, 20);

  doc.setFontSize(11);

  doc.text(`Route: ${data.routeName}`, 20, 40);
  doc.text(`Distance: ${data.distance.toFixed(0)} NM`, 20, 50);
  doc.text(`Fuel Consumption: ${data.fuel.toFixed(1)} T`, 20, 60);
  doc.text(`Total Cost: $${data.cost.toFixed(0)}`, 20, 70);
  doc.text(`Estimated Hours: ${data.hours.toFixed(1)}`, 20, 80);
  doc.text(`ETA: ${data.eta}`, 20, 90);

  doc.text(
    `Wave Height: ${data.waveHeight !== null ? data.waveHeight + ' m' : 'N/A'}`,
    20,
    100
  );

  // Risk logic
  let risk = 'LOW';

  if ((data.waveHeight ?? 0) > 2.5) risk = 'MEDIUM';
  if ((data.waveHeight ?? 0) > 4) risk = 'HIGH';

  doc.text(`Weather Risk: ${risk}`, 20, 110);

  doc.setFontSize(10);
  doc.text('Generated by Maritime Voyage Intelligence SaaS', 20, 140);

  doc.save('voyage-report.pdf');
}
